version: '3'

services:
  app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./django-project:/usr/src/app
    command: >
      sh -c " python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py add_admin_user &&
          python manage.py runserver 0.0.0.0:8000"  
    depends_on:
      # - rabbitmq
      - redis


  
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

  
  # rabbitmq:
  #   image: rabbitmq:alpine
  #   ports: 
  #     - '8001:5672'


  celery:
    restart: always
    build:
      context: .
    command: celery -A myshop worker -l info
    volumes:
      - ./django-project:/usr/src/app
    depends_on:
      - redis
